### ISSUE TITLE
Purpose of MR.AspNetCore.Pagination.Swashbuckle package

### ISSUE THREAD

**Issue by a-a-k** [mrahhal/MR.AspNetCore.Pagination#10]
I really can't figure this out. We already get query parameters while using common MR.AspNetCore.Pagination package, isn't it? Also, it doesn't work with Swashbuckle over v.6.2.3.

**Comment by mrahhal** [comment]
Check the [ApiWithSwashbuckle sample](https://github.com/mrahhal/MR.AspNetCore.Pagination/tree/main/samples/ApiWithSwashbuckle) for an example that uses it.

As mentioned in the README, calling [`ConfigurePagination`](https://github.com/mrahhal/MR.AspNetCore.Pagination/blob/c794ec3ffb7f2b4ccad150ce0f049fbd2a2f1a2a/samples/ApiWithSwashbuckle/Program.cs#L19) when configuring swagger will add a swagger filter that detects actions that return paginated results so that the appropriate params are added to the swagger document automatically, without you having to add them manually.

Without using it, the api will show up as:

![Screenshot_103](https://github.com/mrahhal/MR.AspNetCore.Pagination/assets/4404199/5288d36a-350d-46bc-bae5-9ec0f7a43db4)

Using it, the pagination params are added:

![Screenshot_102](https://github.com/mrahhal/MR.AspNetCore.Pagination/assets/4404199/2374fbc6-f47c-4e99-9845-f8562b476b64)

As for v6.2.3 of Swashbuckle, the ApiWithSwashbuckle sample linked above uses this particular version and it seems to be working for me just fine.

https://github.com/mrahhal/MR.AspNetCore.Pagination/blob/c794ec3ffb7f2b4ccad150ce0f049fbd2a2f1a2a/samples/ApiWithSwashbuckle/ApiWithSwashbuckle.csproj#L11

What do you mean by "it doesn't work"?

**Comment by a-a-k** [comment]
When I don't use `ConfigurePagination` I see this 

![image](https://github.com/mrahhal/MR.AspNetCore.Pagination/assets/5455861/6e4694ea-4229-49c4-b876-0344d29c0852)

and this duplicates, when `ConfigurePagination` in use

![image](https://github.com/mrahhal/MR.AspNetCore.Pagination/assets/5455861/8214772f-57e5-4112-803b-1ce6851d4d8c)

And about Swashbuckle - I meant the package doesn't work for Swashbuckle packages from v6.3.0 and above.

**Comment by mrahhal** [comment]
That's because you probably have the pagination params defined in your action's route config. This package centers around [`IPaginationService`](https://github.com/mrahhal/MR.AspNetCore.Pagination/blob/c794ec3ffb7f2b4ccad150ce0f049fbd2a2f1a2a/src/MR.AspNetCore.Pagination/PaginationService.cs#L11) which will directly read query params. So you don't really need to specify these params manually which you seem to be doing here. That's the whole point actually (if that's not the case, I'm gonna need a proper repro/code to look at). Please check the api actions in the sample I linked if you need a reference in code of what the intended usage looks like.

> And about Swashbuckle - I meant the package doesn't work for Swashbuckle packages from v6.3.0 and above.

Swashbuckle might have introduced a breaking change there, I will have to have a look.

**Comment by a-a-k** [comment]
شكرا

**Comment by mrahhal** [comment]
Swashbuckle problem should be fixed in the newly released v2.2.0.
