### ISSUE TITLE
MR.AspNetCore.Pagination.Swashbuckle Performance problems

### ISSUE THREAD

**Issue by middiu** [mrahhal/MR.AspNetCore.Pagination#12]
Hello there, 

I'm facing some performance issue with **MR.AspNetCore.Pagination.Swashbuckle** package, and in particular when I enable pagination:

````
 builder.Services.AddPagination(options =>
 {
     options.DefaultSize = 100;
     options.MaxSize = 1000;
 });

 options.ConfigurePagination();
````

When I expand one the API section the page freeze and it takes about 10 minutes before getting loaded with pagination parameters:
![image](https://github.com/user-attachments/assets/ed2b6d3a-bc14-4e6b-a986-6f25d2eec41b)

![image](https://github.com/user-attachments/assets/99fa66b2-aea9-4b8c-ab42-c57e28082d02)

this is my endpoint code:
````
        public async Task<ActionResult<OffsetPaginationResult<ProjectAlerts>>> GetAlerts([FromRoute] string vertical, [FromRoute] int tenantId, [FromRoute] int prjId, [FromQuery] OffsetQueryModel offsetQueryModel)
````

is there anything wrong in the way a bind **OffsetQueryModel**  or in the way I setup pagination?

**Comment by mrahhal** [comment]
Hello. This package uses swagger-ui as is without any changes. It could be a problem with swagger itself, but you should start by looking into where the time is spent when that spinner is loading. Are there console logs or warnings? Does this happen only with this particular api? You can also run your browser's profiler, and it will tell you where that time is being spent. In addition, also try removing that `OffsetQueryModel` from the binding and see if that makes a difference, since although I can't see any problem with it, I don't use it this way.

10 mins there sounds to me like a reactivity issue inside swagger-ui. Maybe there's something it's not expecting there.

**Comment by middiu** [comment]
The problem seems to be the Controller return type. If I change 
````
public async Task<ActionResult<OffsetPaginationResult<ProjectAlerts>>> GetAlerts([FromRoute] string vertical, [FromRoute] int tenantId, [FromRoute] int prjId, [FromQuery] OffsetQueryModel offsetQueryModel)
````

to 

````
public async Task<IActionResult> GetAlerts([FromRoute] string vertical, [FromRoute] int tenantId, [FromRoute] int prjId, [FromQuery] OffsetQueryModel offsetQueryModel)
````

everything is back to normal speed.
I tried removing **OffsetQueryModel** as well but it doesn't have any impact on that.

I think this is not a problem of this library, but something I would need to check with Swagger team.

Cheers

**Comment by mrahhal** [comment]
Thanks for confirming. But this still does not answer where that time is spent. Is it a request in the network tab, an error in the console log, and reactivity issue with the ui not updating until much later? etc, etc
Depending on the answer, we can be sure whether this is a swagger problem or not.

Curiously, I use this exact return type in many places in one of my apps and swagger ui can display it just fine. What does your `ProjectAlerts` class look like?

**Comment by mrahhal** [comment]
I'm closing this as there is nothing to do in this package. Please reopen if you still have issues.
